# Generated by Django 2.2.5 on 2021-11-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20211117_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bedroomss',
            new_name='bedrooms',
        ),
    ]
